// Roster for India's Got Latent, Season 1 & Season 2
// type: 'panel' | 'contestant'
// panels: which panels they sat on (quick revision, some guests like Aashish did multiple)
// blurb: who they are + which episode and who they judged with (shown when no photo exists)
// wiki: Wikipedia page title used to auto-fetch a photo
// showScore: the score (out of 10) they got on the actual episode, fill these in as you find
//            them; the "Audience Winners" section compares this to the app's audience average.

module.exports = [
  // ---------------- CORE ----------------
  { id: 'samay-raina', name: 'Samay Raina', type: 'panel',
    panels: ['S1 E1–E12', 'S2 E1', 'S2 E2'],
    blurb: 'Creator, host and permanent judge across every episode. The reason any of this exists. Ran a season-long roast of Balraj for never contributing prize money.',
    joke: 'Iss show ka koi point nahi hai, just like life',
    wiki: 'Samay Raina', insta: 'maisamayhoon' },
  { id: 'balraj-ghai', name: 'Balraj Singh Ghai', type: 'panel',
    panels: ['S1 (recurring)', 'S2 E1', 'S2 E2'],
    blurb: 'The Habitat founder ("Habitat inke papa ka hai") and recurring co-judge through S1; on both S2 panels. Gave a brutal 3.6 in E1, then secretly let a rejected rapper perform anyway.',
    joke: 'Bhai, maine life mein bahut musicians sune hain', insta: 'balrajghai' },

  // ---------------- SEASON 1 GUEST PANELS ----------------
  { id: 'raftaar', name: 'Raftaar', type: 'panel', panels: ['S1 E1'],
    blurb: 'Rapper. Judged the premiere (E1) with Sahil Kale, got roasted all episode about his divorce, leaned in, and added ₹30k to the prize pool.',
    joke: 'Yeah, for my age, anyone I meet will be a mommy',
    wiki: 'Raftaar', insta: 'raftaarmusic' },
  { id: 'sahil-kale', name: 'Sahil Kale', type: 'panel', panels: ['S1 E1', 'S1 Bonus E1'],
    blurb: 'E1 judge with Raftaar, the self-declared nepotism-quota pick who countered Balraj\'s 3.6 with a 9.9 for the same act. Returned for Bonus E1 with Arpit Bala, Bhappa and Amin Khan.',
    joke: 'I was Samay\'s manager and now I am happy, that\'s what I am', insta: 'sahil_black' },
  { id: 'anshu-bisht', name: 'Anshu Bisht', type: 'panel', panels: ['S1 E2'],
    blurb: 'Gaming creator (GamerFleet), the show\'s first gamer judge. E2 panel with Nishant Tanwar and Karan Singh Magic.',
    joke: 'Bhai relate hota toh 10 deta na', insta: 'gamerfleet' },
  { id: 'nishant-tanwar', name: 'Nishant Tanwar', type: 'panel', panels: ['S1 E2', 'S1 E6'],
    blurb: 'Stand-up comedian (Joke Singh). Two panels: E2 with Anshu Bisht and Karan Singh Magic, E6 with Vipul Goyal and Sonali Thakker.',
    wiki: 'Joke Singh', insta: 'jokesingh',
    joke: 'Bhai aapko latent nahi, latex ki zaroorat thi' },
  { id: 'karan-singh-magic', name: 'Karan Singh Magic', type: 'panel', panels: ['S1 E2'],
    blurb: 'Magician. E2 panel with Anshu Bisht and Nishant Tanwar, volunteered for a mind-reading act and prematurely blurted his chosen date.',
    joke: 'Recently he did a very big trick where he disappeared from the YouTube algorithm',
    jokeBy: 'Samay, introducing him',
    wiki: 'Karan Singh Magic', insta: 'karansinghmagic' },
  { id: 'aashish-solanki', name: 'Aashish Solanki', type: 'panel', panels: ['S1 E3', 'S1 E12', 'S2 E1'],
    blurb: 'Stand-up comedian (Pretty Good Roast Show). Three panels: E3 with Uorfi Javed and Yashraj, the E12 finale with Rakhi Sawant, Maheep Singh and Yashraj, and the S2 premiere with Alia Bhatt and Sharvari.',
    joke: 'Aapke show mein aaya hoon jahan koi punchline censor nahi hoti', insta: 'ashishsolanki_1' },
  { id: 'urfi-javed', name: 'Uorfi Javed', type: 'panel', panels: ['S1 E3'],
    blurb: 'Internet fashion icon, introduced as "Kim Kardashian from Kurla", got a mock on-stage proposal from a contestant. E3 panel with Aashish Solanki and Yashraj.',
    joke: 'Isse pehle kaafi achha feel kar rahi thi main',
    wiki: 'Urfi Javed', insta: 'urf7i' },
  { id: 'yashraj', name: 'Yashraj', type: 'panel', panels: ['S1 E3', 'S1 E12'],
    blurb: 'Rapper. E3 panel with Aashish Solanki and Uorfi Javed (got roasted about failed musicians becoming IGL judges); returned for the E12 finale.',
    joke: 'E.P. coming out today', insta: 'yashrajmusic' },
  { id: 'maheep-singh', name: 'Maheep Singh', type: 'panel', panels: ['S1 E4', 'S1 E12'],
    blurb: 'Comedian. E4 panel with Neeti Palta and Amit Tandon, the episode\'s main roast target for asking everyone "mummy kaisi hai"; returned for the E12 finale where he clashed with Rakhi Sawant.',
    joke: 'Haqeeqat nahi ho, tum mera bharam ho; jhoothe toh sab hain, tum thodi kam ho', insta: 'imaheepsingh' },
  { id: 'neeti-palta', name: 'Neeti Palta', type: 'panel', panels: ['S1 E4'],
    blurb: 'Stand-up comedian. E4 panel with Maheep Singh and Amit Tandon.',
    joke: 'India mein sab aurton se delivery maangte rehte hain', insta: 'neetipalta' },
  { id: 'amit-tandon', name: 'Amit Tandon', type: 'panel', panels: ['S1 E4'],
    blurb: 'Stand-up comedian ("married guy" jokes). E4 panel with Maheep Singh and Neeti Palta, scored a stoner rapper 420.',
    joke: 'Maine diya hai 420', insta: 'amitandon' },
  { id: 'kunal-kamra', name: 'Kunal Kamra', type: 'panel', panels: ['S1 E5'],
    blurb: 'Stand-up comedian. E5 panel with Atul Khatri, spent the night grilling contestants about their situationships.',
    joke: 'If you don\'t want your parents to die, just start doing stand-up comedy',
    wiki: 'Kunal Kamra', insta: 'kuna_kamra' },
  { id: 'atul-khatri', name: 'Atul Khatri', type: 'panel', panels: ['S1 E5'],
    blurb: 'Stand-up comedian. E5 panel with Kunal Kamra, negotiated scores with a contestant\'s dad sitting in the audience.',
    joke: 'Because of your dad I\'ve increased marks', wiki: 'Atul Khatri', insta: 'atul_khatri' },
  { id: 'vipul-goyal', name: 'Vipul Goyal', type: 'panel', panels: ['S1 E6'],
    blurb: 'Stand-up comedian (Humorously Yours). E6 panel with Nishant Tanwar and Sonali Thakker.',
    wiki: 'Vipul Goyal', insta: 'vipulgoyal' },
  { id: 'sonali-thakker', name: 'Sonali Thakker', type: 'panel', panels: ['S1 E6'],
    blurb: 'Stand-up comedian. E6 panel with Vipul Goyal and Nishant Tanwar.', insta: 'sonalithakker' },
  { id: 'ravi-gupta', name: 'Ravi Gupta', type: 'panel', panels: ['S1 E7'],
    blurb: 'Comedian. E7 panel with Rahgir and Saurabh Pandey.' },
  { id: 'rahgir', name: 'Rahgir', type: 'panel', panels: ['S1 E7'],
    blurb: 'Poet-musician. E7 panel with Ravi Gupta and Saurabh Pandey.', insta: 'rahgirlive' },
  { id: 'saurabh-pandey', name: 'Saurabh Pandey', type: 'panel', panels: ['S1 E7'],
    blurb: 'Comedian. E7 panel with Ravi Gupta and Rahgir.', insta: 'comicsaurabh' },
  { id: 'poonam-pandey', name: 'Poonam Pandey', type: 'panel', panels: ['S1 E8'],
    blurb: 'Model and actress. E8 panel with Vidit Gujrathi, Sagar Shah and Vivek.',
    wiki: 'Poonam Pandey', insta: 'poonampandeyreal' },
  { id: 'vidit-gujrathi', name: 'Vidit Gujrathi', type: 'panel', panels: ['S1 E8'],
    blurb: 'Chess Grandmaster. E8 panel with Poonam Pandey, Sagar Shah and Vivek.',
    wiki: 'Vidit Gujrathi', insta: 'viditchess' },
  { id: 'sagar-shah', name: 'Sagar Shah', type: 'panel', panels: ['S1 E8'],
    blurb: 'ChessBase India founder. E8 panel with Poonam Pandey, Vidit Gujrathi and Vivek.',
    wiki: 'Sagar Shah', insta: 'sagarchess' },
  { id: 'vivek', name: 'Vivek Desai', type: 'panel', panels: ['S1 E8'],
    blurb: 'Magician-mentalist. E8 panel with Poonam Pandey, Vidit Gujrathi and Sagar Shah.', insta: 'vivekmagic' },
  { id: 'deepak-kalal', name: 'Deepak Kalal', type: 'panel', panels: ['S1 E9'],
    blurb: 'Internet personality. E9 panel with Manan Desai and Agu Stanley.', insta: 'deepakkalal',
    joke: 'Videos mein main tatti, harami dikhata hoon, reality mein Mahatma Gandhi jaisa dayalu hoon' },
  { id: 'manan-desai', name: 'Manan Desai', type: 'panel', panels: ['S1 E9'],
    blurb: 'Comedian (The Comedy Factory). E9 panel with Deepak Kalal and Agu Stanley.',
    wiki: 'Manan Desai', insta: 'manandesai',
    joke: 'Tum chor bazaar mein shopping karte ho? Main toh tumhare ghar mein shopping karta hoon' },
  { id: 'agu-stanley', name: 'Agu Stanley', type: 'panel', panels: ['S1 E9'],
    blurb: 'Creator (StanBoss). E9 panel with Deepak Kalal and Manan Desai.', insta: 'stanboss1' },
  { id: 'tanmay-bhat', name: 'Tanmay Bhat', type: 'panel', panels: ['S1 E10'],
    blurb: 'Comedian and streamer. E10 panel with Raghu Ram and Sid Warrier.',
    wiki: 'Tanmay Bhat', insta: 'tanmaybhat' },
  { id: 'raghu-ram', name: 'Raghu Ram', type: 'panel', panels: ['S1 E10'],
    blurb: 'Roadies legend. E10 panel with Tanmay Bhat and Sid Warrier.',
    wiki: 'Raghu Ram', insta: 'instaraghu',
    joke: 'Ye Roadies ki zubaan hai, bata bhai, gaand kaise dhota hai!' },
  { id: 'sid-warrier', name: 'Sid Warrier', type: 'panel', panels: ['S1 E10'],
    blurb: 'Neurologist and YouTuber. E10 panel with Tanmay Bhat and Raghu Ram.', insta: 'sidwarrier' },
  { id: 'bharti-singh', name: 'Bharti Singh', type: 'panel', panels: ['S1 E11'],
    blurb: 'Comedy superstar. E11 panel with husband Haarsh Limbachiyaa, Tony Kakkar and Drew.',
    wiki: 'Bharti Singh', insta: 'bharti.laughterqueen',
    joke: 'Aapko pata hai, mote logo ki wajah se house full lagta hai' },
  { id: 'tony-kakkar', name: 'Tony Kakkar', type: 'panel', panels: ['S1 E11'],
    blurb: 'Singer-composer. E11 panel with Bharti Singh, Haarsh Limbachiyaa and Drew.',
    wiki: 'Tony Kakkar', insta: 'tonykakkar',
    joke: 'Mile ho tum humko bade naseebo se, hilaya hai humne, haathon ki lakeer hai' },
  { id: 'drew', name: 'Drew Hicks', type: 'panel', panels: ['S1 E11'],
    blurb: 'American creator famous for his fluent Bhojpuri. E11 panel with Bharti Singh, Haarsh Limbachiyaa and Tony Kakkar.', insta: 'indiadrew77' },
  { id: 'rakhi-sawant', name: 'Rakhi Sawant', type: 'panel', panels: ['S1 E12'],
    blurb: 'Drama queen of Indian TV. E12 finale panel with Maheep Singh, Aashish Solanki and Yashraj, the legendary clash episode.',
    wiki: 'Rakhi Sawant', insta: 'rakhisawant2511',
    joke: 'Main late ho gayi, Maheep ji mere undergarment leke bhaag gaye the' },
  { id: 'haarsh-limbachiyaa', name: 'Haarsh Limbachiyaa', type: 'panel', panels: ['S1 E11', 'S2 E2'],
    blurb: 'Producer-comedian and Bharti\'s husband. S1 E11 panel with Bharti, Tony Kakkar and Drew; back for S2 E2 with Kiku Sharda, Chandan Prabhakar and Balraj.',
    wiki: 'Haarsh Limbachiyaa', insta: 'haarshlimbachiyaa30' },

  // ---------------- SEASON 1 BONUS / MEMBERS-ONLY PANELS ----------------
  { id: 'madhur-virli', name: 'Madhur Virli', type: 'panel', panels: ['S1 Bonus E4'],
    blurb: 'Comedian (Madhur Model). Bonus E4 panel with Seedhe Maut and Kaustubh Agarwal.' },
  { id: 'kaustubh-agarwal', name: 'Kaustubh Agarwal', type: 'panel', panels: ['S1 Bonus E4'],
    blurb: 'Comedian and Latent regular. Bonus E4 panel with Seedhe Maut and Madhur Virli.', insta: 'kaustubh_agarwal3' },
  { id: 'seedhe-maut', name: 'Seedhe Maut', type: 'panel', panels: ['S1 Bonus E4'],
    blurb: 'Delhi rap duo (Encore ABJ & Calm). Bonus E4 panel with Madhur Virli and Kaustubh Agarwal.',
    wiki: 'Seedhe Maut', insta: 'seedhemaut' },
  { id: 'badshah', name: 'Badshah', type: 'panel', panels: ['S1 Bonus E2'],
    blurb: 'Rap superstar. Bonus E2 panel with Siddhant Chaturvedi, Gursimran Khamba and Balraj.',
    wiki: 'Badshah (rapper)', insta: 'badboyshah',
    joke: 'Done bro, we\'ll finance you' },
  { id: 'gursimran-khamba', name: 'Gursimran Khamba', type: 'panel', panels: ['S1 Bonus E2'],
    blurb: 'Comedian, AIB co-founder. Bonus E2 panel with Badshah, Siddhant Chaturvedi and Balraj.',
    wiki: 'Gursimran Khamba', insta: 'gursimrankhamba' },
  { id: 'rohan-joshi', name: 'Rohan Joshi', type: 'panel', panels: ['S1 Bonus E5'],
    blurb: 'Comedian, AIB co-founder. Bonus E5 panel with Sahil Shah, Vaibhav Sethia and Chandni Anand Ghai.',
    wiki: 'Rohan Joshi (comedian)', insta: 'mojorojo' },
  { id: 'ashish-chanchlani', name: 'Ashish Chanchlani', type: 'panel', panels: ['S1 Bonus E6'],
    blurb: 'YouTube megastar. Bonus E6 panel, the episode that broke the internet.',
    wiki: 'Ashish Chanchlani', insta: 'ashishchanchlani' },
  { id: 'ranveer-allahbadia', name: 'Ranveer Allahbadia', type: 'panel', panels: ['S1 Bonus E6'],
    blurb: 'Podcaster (BeerBiceps). Bonus E6, his question sparked the February 2025 firestorm that took the show offline.',
    wiki: 'Ranveer Allahbadia', insta: 'ranveerallahbadia' },
  { id: 'jaspreet-singh', name: 'Jaspreet Singh', type: 'panel', panels: ['S1 Bonus E6'],
    blurb: 'Stand-up comedian. Bonus E6 panel with Ashish Chanchlani, Ranveer and Apoorva.', insta: 'jaspreetsingh' },
  { id: 'apoorva-mukhija', name: 'Apoorva Mukhija', type: 'panel', panels: ['S1 Bonus E6'],
    blurb: 'Creator "The Rebel Kid". Bonus E6 panel, caught in the same storm as the episode.',
    wiki: 'Apoorva Mukhija', insta: 'the.rebel.kid' },

  { id: 'siddhant-chaturvedi', name: 'Siddhant Chaturvedi', type: 'panel', panels: ['S1 Bonus E2'],
    blurb: 'Gully Boy actor. Bonus E2 panel with Badshah, Gursimran Khamba and Balraj.',
    wiki: 'Siddhant Chaturvedi', insta: 'siddhantchaturvedi',
    joke: '8 for the painting, 2 for the poetry you recited for me, so 10' },
  { id: 'avika-gor', name: 'Avika Gor', type: 'panel', panels: ['S1 Bonus E3'],
    blurb: 'Balika Vadhu star. Bonus E3 panel with Devesh Dixit, Shashwat Maheshwari and Balraj.',
    wiki: 'Avika Gor', insta: 'avikagor' },
  { id: 'devesh-dixit', name: 'Devesh Dixit', type: 'panel', panels: ['S1 Bonus E3'],
    blurb: 'Stand-up comedian. Bonus E3 panel with Avika Gor, Shashwat Maheshwari and Balraj.',
    insta: 'dixitdevesh' },
  { id: 'shashwat-maheshwari', name: 'Shashwat Maheshwari', type: 'panel', panels: ['S1 Bonus E3'],
    blurb: 'Stand-up comedian. Bonus E3 panel with Avika Gor, Devesh Dixit and Balraj.', insta: 'kaatilkabootar' },
  { id: 'sahil-shah', name: 'Sahil Shah', type: 'panel', panels: ['S1 Bonus E5'],
    blurb: 'Stand-up comedian (EIC). Bonus E5 panel with Rohan Joshi, Vaibhav Sethia and Chandni Anand Ghai.',
    wiki: 'Sahil Shah', insta: 'sahilbulla' },
  { id: 'vaibhav-sethia', name: 'Vaibhav Sethia', type: 'panel', panels: ['S1 Bonus E5'],
    hidden: true, // was not actually on the show — kept for data/votes but excluded from the app
    blurb: 'Stand-up comedian. Bonus E5 panel with Rohan Joshi, Sahil Shah and Chandni Anand Ghai.' },
  { id: 'chandni-bhabhda', name: 'Chandni Anand Ghai', type: 'panel', panels: ['S1 Bonus E5'],
    blurb: 'Balraj\'s wife and The Habitat co-force. Bonus E5 panel with Rohan Joshi, Sahil Shah and Vaibhav Sethia.', insta: 'chandni_a' },

  { id: 'arpit-bala', name: 'Arpit Bala', type: 'panel', panels: ['S1 Bonus E1'],
    blurb: 'Rapper-comedian (Arpit Balabantaray). Bonus E1 panel with Bhappa, Sahil Kale and Amin Khan.', insta: 'arpitbala19' },
  { id: 'bappa', name: 'Bhappa (Siddharth Tewatia)', type: 'panel', panels: ['S1 Bonus E1'],
    blurb: 'Creator Siddharth Tewatia aka Bhappa. Bonus E1 panel with Arpit Bala, Sahil Kale and Amin Khan.', insta: 'iambhappa' },

  // ---------------- SEASON 2 PANELS ----------------
  { id: 'alia-bhatt', name: 'Alia Bhatt', type: 'panel', panels: ['S2 E1'],
    blurb: 'Bollywood A-lister. S2 premiere panel with Sharvari and Aashish Solanki (Alpha promo).',
    wiki: 'Alia Bhatt', insta: 'aliaabhatt' },
  { id: 'sharvari', name: 'Sharvari', type: 'panel', panels: ['S2 E1'],
    blurb: 'Actress. S2 premiere panel with Alia Bhatt and Aashish Solanki (Alpha promo).',
    wiki: 'Sharvari', insta: 'sharvari' },
  { id: 'kiku-sharda', name: 'Kiku Sharda', type: 'panel', panels: ['S2 E2'],
    blurb: 'Comedy icon (Kapil Sharma Show). S2 E2 panel with Chandan Prabhakar, Haarsh Limbachiyaa and Balraj.',
    wiki: 'Kiku Sharda', insta: 'kikusharda' },
  { id: 'chandan-prabhakar', name: 'Chandan Prabhakar', type: 'panel', panels: ['S2 E2'],
    blurb: 'Comedy icon (Chandu!). S2 E2 panel with Kiku Sharda, Haarsh Limbachiyaa and Balraj.',
    wiki: 'Chandan Prabhakar', insta: 'chandanprabhakar' },

  // ---------------- SEASON 1 CONTESTANTS ----------------
  { id: 'jyoti-sharma', name: 'Jyoti Sharma', type: 'contestant', panels: ['S1 E1'],
    blurb: 'Co-won E1 with a Hinglish rap about her ex, guessed herself 6.5 and the panel average landed exactly 6.5.',
    joke: 'Usko interest aaya tha mommies mein, now he is dating a 30-year-old, and he is 23',
    showScore: 6.5 },
  { id: 'vedant-modi', name: 'Vedant Modi', type: 'contestant', panels: ['S1 E1'],
    blurb: 'Co-won E1 with a mentalist act, predicted a ₹100 note\'s serial number through audience calculator math.',
    showScore: null },
  { id: 'anant-upadhyay', name: 'Anant Upadhyay', type: 'contestant', panels: ['S1 E2'],
    blurb: 'Co-winner of Episode 2.', showScore: null },
  { id: 'suryansh-veer', name: 'Suryansh Pandey & Veer', type: 'contestant', panels: ['S1 E2'],
    blurb: 'Reggae-rap duo living the rasta life, co-won E2 with tracks off their album "420".',
    joke: 'Khana banao, khao, so; gaana banao, gao, so', showScore: null },
  { id: 'ddsry', name: 'Deepak Yadav (DDSRY)', type: 'contestant', panels: ['S1 E3'],
    blurb: 'Won E3 with a poem on jealousy, forgot his lines, fumbled his phone password, read it off the screen anyway, and his self-score of 7 matched the average exactly.',
    joke: 'Ek saal se wahi poetry kar raha hoon, aaj khatam kar raha hoon',
    showScore: 7 }, // self 7 = announced average 7
  { id: 'hard-shivam', name: 'Hard Shivam', type: 'contestant', panels: ['S1 E4'],
    blurb: 'Won E4 with a stand-up beatboxing act capped by an energetic English-Hindi rap.', showScore: null },
  { id: 'naman-arora', name: 'Naman Arora', type: 'contestant', panels: ['S1 E5'],
    blurb: 'Won E5 with a high-energy "ek tarfa pyaar" shayari set, Samay brought him back on stage as "the savior of the show".',
    joke: 'YouTube nahi, Sony hai tu!', showScore: null, insta: 'namanarora' },
  { id: 'sewashree-boruah', name: 'Sewashree Boruah', type: 'contestant', panels: ['S1 E6'],
    blurb: 'Winner of Episode 6.', showScore: null },
  { id: 'parneet-singh', name: 'Parneet Singh', type: 'contestant', panels: ['S1 E7'],
    blurb: 'Winner of Episode 7.', showScore: null },
  { id: 'pravin-bhairwa', name: 'Pravin Bhairwa', type: 'contestant', panels: ['S1 E8'],
    blurb: 'Winner of Episode 8 with heartfelt poetry.', showScore: null },
  { id: 'kushal-bhanushali', name: 'Kushal Bhanushali', type: 'contestant', panels: ['S1 E9', 'S1 E11'],
    blurb: 'Winner of Episode 9 AND co-winner of Episode 11. Double latent.', showScore: null, insta: 'kushal.bhanushali' },
  { id: 'banti-banerjee', name: 'Banti Banerjee', type: 'contestant', panels: ['S1 E10'],
    blurb: 'Co-winner of Episode 10.', showScore: null },
  { id: 'mysterious-kayden', name: 'Mysterious Kayden', type: 'contestant', panels: ['S1 E10'],
    blurb: 'Co-winner of Episode 10.', showScore: null },
  { id: 'anmol-sharma', name: 'Anmol Sharma', type: 'contestant', panels: ['S1 E11'],
    blurb: 'Co-winner of Episode 11.', showScore: null },
  { id: 'yuvraj-gupta', name: 'Yuvraj Gupta', type: 'contestant', panels: ['S1 E12'],
    blurb: 'Co-winner of the Season 1 finale.', showScore: null },
  { id: 'khushi-saini', name: 'Khushi Saini', type: 'contestant', panels: ['S1 E12'],
    blurb: 'Co-winner of the Season 1 finale.', showScore: null },

  { id: 'decibel-crew', name: 'Decibel Crew', type: 'contestant', panels: ['S1 E1'],
    blurb: 'Beatbox duo on the premiere, pulled 10s from Samay and Raftaar but the average didn\'t match their guess.',
    joke: 'Humari tag team hai, uska naam BJ hai', showScore: null },
  { id: 'magnus-chess-rapper', name: '"Magnus Carlsen" (chess rapper)', type: 'contestant', panels: ['S1 E1'],
    blurb: 'Came from Delhi under a grandmaster stage name to diss-rap Samay in actual chess moves, ending on \'Qc1 checkmate\'.',
    joke: 'Chote balls nahi pasand, bullet khelu, haar jao, mera Samay rahe na', showScore: null },

  // ------- Season 1 viral non-winners (episode numbers unconfirmed) -------
  { id: 'sharon-verma', name: 'Sharon Verma', type: 'contestant', panels: ['S1'],
    blurb: '"Sharon from Bihar", the self-described weak independent woman. Didn\'t win, went mega viral.', showScore: null, insta: 'sharonverma' },
  { id: 'keshav-jha', name: 'Keshav Jha', type: 'contestant', panels: ['S1'],
    blurb: 'Went viral off the back of his Latent appearance despite not winning.', showScore: null, insta: 'keshav.jha' },
  { id: 'amin-khan', name: 'Amin Khan', type: 'contestant', panels: ['S1', 'S1 Bonus E1 (panel)'],
    blurb: 'The bouncer-turned-podcaster. No trophy as a contestant, but came back as a Bonus E1 panelist with Arpit Bala, Bhappa and Sahil Kale.', showScore: null },
  { id: 'manmeet', name: 'Manmeet', type: 'contestant', panels: ['S1'],
    blurb: 'Rapper who came back from Canada for the stage. Didn\'t win, still iconic.', showScore: null },
  { id: 'mimic-suryansh', name: 'Mimic Suryansh', type: 'contestant', panels: ['S1'],
    blurb: 'His Sanjay Dutt parody skit went viral after the episode.', showScore: null },

  // ------- discovered via episode transcripts -------
  { id: 'severus-hydro', name: 'Severus Hydro & Himanshu', type: 'contestant', panels: ['S1 E2'],
    blurb: 'Corporate-life rap duo, notice periods, chess losses and Adani stocks. Panel average 8.15, still no win.',
    joke: 'H is silent, music is loud', showScore: 8.15 },
  { id: 'devapreet-bhavsar', name: 'Devapreet Bhavsar', type: 'contestant', panels: ['S1 E3'],
    blurb: 'Breakup poet clutching a guitar he can\'t play, mock-proposed to Uorfi on stage; guessed 8.5, got 6.5.',
    joke: 'Teen ladkiyon ko propose kiya hai, teeno se mana suna', showScore: 6.5 },
  { id: 'ritik-kadam', name: 'Ritik Kadam', type: 'contestant', panels: ['S1 E3'],
    blurb: 'Stand-up on Indians vs gore log and a potty-training masterclass, guessed 7.5, got 6.',
    joke: 'Sabse pehle 420 legal kar dunga… ganja bhai', showScore: 6 },
  { id: 'pranav-adwaita', name: 'Pranav Subramanyam & Adwaita', type: 'contestant', panels: ['S1 E3'],
    blurb: 'Student musical duo (one brought a flute he never played), scored a massive 9.5 but guessed 8.5, so no win.',
    joke: 'Musician poori mehnat karta hai, kaam nahi chalta, phir India\'s Got Latent pe judge ban jaata hai',
    showScore: 9.5 },
  { id: 'bachcha-rohit', name: 'Bachcha (Rohit)', type: 'contestant', panels: ['S1 E4'],
    blurb: '18-year-old who sang a self-written romantic song… for his friend\'s girlfriend, on request.',
    joke: 'Wo meri nahi, mere dost ki girlfriend hai, usne bola mere liye song likh de', showScore: null },
  { id: 'shivani-rai', name: 'Shivani Rai', type: 'contestant', panels: ['S1 E4'],
    blurb: 'Spoken-word poet on men, women and earning, pulled 8s and 9s from the panel.',
    joke: 'Maine tumhe misogynist nahi bola, maine khud ko bola', showScore: null },
  { id: 'kiran-holkar', name: 'Kiran Holkar', type: 'contestant', panels: ['S1 E4'],
    blurb: 'Sang an English song after scoring herself a straight 10, and never got the mic test she wanted.',
    joke: 'Agar mic test mil jaata toh thoda kuch aur ho jaata', showScore: null },

  { id: 'shweta-singh', name: 'Shweta Singh', type: 'contestant', panels: ['S1 E5'],
    blurb: 'Recited breakup shayari about a cheating ex, then got grilled by Kunal Kamra about the situationship.',
    joke: 'Tera number feed hai dil mein, kaise delete karun?', showScore: null },
  { id: 'saurav-vaishnav', name: 'Saurav Vaishnav', type: 'contestant', panels: ['S1 E5'],
    blurb: 'Jaipur stand-up on scientists hunting water on other planets, guessed 9, got 7.',
    joke: 'Ek planet ho sakta hai jahan samandar mein beer ki lehren uth rahi hain', showScore: 7 },
  { id: 'sanjana-chatwani', name: 'Sanjana Chatwani', type: 'contestant', panels: ['S1 E5'],
    blurb: 'Sang a Bollywood love song and flexed a world record: smallest finger painting, 35 seconds, 1x1.5 inch canvas. Average: 5.5.',
    showScore: 5.5 },

  // ---------------- SEASON 2 CONTESTANTS ----------------
  { id: 'avinash-agarwal', name: 'Avinash Agarwal', type: 'contestant', panels: ['S2 E1'],
    blurb: 'The "Indian Donald Trump". Won the S2 premiere with a perfect 10 average, and guessed 10 on himself ("the highest number I can count to").',
    showScore: 10, insta: 'avinashagarwal' }, // panel average announced as 10 in the episode
  { id: 'sukrut-deo', name: 'Sukrut Deo', type: 'contestant', panels: ['S2 E1'],
    blurb: 'S2 premiere poet, straight 10s from the whole panel; Alia said she left inspired.',
    showScore: 10, insta: 'sukrutdeo' }, // announced average: 10
  { id: 'suhasini', name: 'Suhasini', type: 'contestant', panels: ['S2 E1'],
    blurb: 'Singer on the S2 premiere, Samay gave 7 ("10 for singing, minus 3 for the writing"), Alia and Sharvari 8, Solanki 6.', showScore: null },
  { id: 'gajendra', name: 'Gajendra Bhai', type: 'contestant', panels: ['S2 E1'],
    blurb: 'S2 premiere performer (of Munjya fame), the panel gave him 9s, a 9.5 and a 10.', showScore: null },
  { id: 'kapil-dinkar', name: 'Kapil Dinkar', type: 'contestant', panels: ['S2 E2'],
    blurb: 'UP cop who won Episode 2 and took home ₹1 lakh.', showScore: null, insta: 'kapildinkar' },
  { id: 'geni-kamki', name: 'Geni Kamki', type: 'contestant', panels: ['S2'],
    blurb: 'Dancer from Arunachal Pradesh whose clip crossed 134M views, outperforming Samay\'s own videos.', showScore: null, insta: 'genikamki' },
];
